# Project information
site_name: 'OkDownloader'
site_description: 'A downloader library base on OkHttp for Java and Android.'
site_author: '2023 OkDownloader Contributors'
site_url: 'https://ydxlt.github.io/okdownloader/'
remote_branch: gh-pages
edit_uri: ""

# Repository
repo_name: 'OkDownloader'
repo_url: 'https://github.com/ydxlt/okdownloader'

# Copyright
copyright: 'Copyright &copy; 2023 OkDownloader Contributors'

# Configuration
theme:
  name: 'material'
  language: 'en'
  favicon: 'images/logo.svg'
  logo: 'images/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ydxlt/okdownloader'

# Navigation
nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Synchronous Download': synchronous_download.md
  - 'Asynchronous Download': asynchronous_download.md
  - 'Transformations': transformations.md
  - 'Transitions': transitions.md
  - 'Extending the Image Pipeline': image_pipeline.md
  - 'Java Compatibility': java_compatibility.md
  - 'FAQ': faq.md
  - 'API ⏏': api/index.html
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md

# CSS
extra_css:
  - 'css/site.css'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Built with https://github.com/squidfunk/mkdocs-material